version: '3'
networks:
  web:
    external: true

services:
  backend-services:
    image: mikeryan56/backend-services:latest
    ports:
    - "5000"
    volumes:
    - .:/code
    labels:
    - "traefik.enable=true" # <== Enable traefik to proxy this container
    - "traefik.http.routers.backend-services-web.rule=Host(`backend-services.devsetgo.com`)" # <== Your Domain Name goes here for the http rule
    - "traefik.http.routers.backend-services-web.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
    - "traefik.http.routers.backend-services-web.middlewares=redirect@file" # <== This is a middleware to redirect to https
    - "traefik.http.routers.backend-services-secured.rule=Host(`backend-services.devsetgo.com`)" # <== Your Domain Name for the https rule
    - "traefik.http.routers.backend-services-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
    - "traefik.http.routers.backend-services-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
    networks:
      - web
      - backend
    # restart:
    #   - "always"
    # healthcheck:
    #   test: curl --fail -s http://localhost:5000/ || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
  # deploy:
  #    replicas: 2
  #    resources:
  #      limits:
  #        cpus: "2"
  #        memory: 100M
networks:
  web:
    external: true
  backend:
    external: false